---
- name: Install CRI-O
  ansible.builtin.apt:
    name: "{{ _k8s_crio_package }}"
    state: present

- name: Hold the CRI-O package
  ansible.builtin.dpkg_selections:
    name: "{{ _k8s_crio_package }}"
    selection: "{{ 'hold' if kubernetes_packages_hold | bool else 'install' }}"

- name: Ensure CRI-O is enabled and running
  ansible.builtin.systemd_service:
    name: crio
    enabled: true
    state: started
