---
- name: Disable swap temporarily
  ansible.builtin.shell: "swapoff -a"
  changed_when: false

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: Create /etc/modules-load.d directory if not exist
  ansible.builtin.file:
    path: "/etc/modules-load.d"
    state: directory
    mode: 0755

- name: Load the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Create cri-o.conf file for sysctl to enable IPv4 routing
  ansible.builtin.copy:
    dest: /etc/sysctl.d/cri-o.conf
    content: |
      net.ipv4.ip_forward = 1
    mode: 0644
  notify: Apply sysctl settings
