---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - python3
      - curl
      - ufw
    state: present
    update_cache: yes

- name: Set default firewall incoming rule
  ansible.builtin.ufw:
    default: deny
    direction: incoming

- name: Set default firewall outgoing rule
  ansible.builtin.ufw:
    default: allow
    direction: outgoing

- name: Allow ssh incoming rule
  ansible.builtin.ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Authorize cni pod network host port
  ansible.builtin.ufw:
    rule: allow
    port: "{{ kubernetes_cni_network.pod_host_port }}"
    proto: tcp
  when: kubernetes_cni_network.pod_host_port != ""

- name: Enable firewall
  ansible.builtin.ufw:
    state: enabled

- name: Swap cri-o netfilter setup
  include_tasks: swap-crio-netfilter-setup.yml
